// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: gbxznafrxqgmcmsovtjd

class SupabaseConfig {
  static const String supabaseUrl = 'https://gbxznafrxqgmcmsovtjd.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdieHpuYWZyeHFnbWNtc292dGpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyNDYwOTEsImV4cCI6MjA4MDgyMjA5MX0.02OX0ZiUYRRmZw027nx_lCU4luYmX0Zt48tMIuczv_Q';
}
